repos:
  # Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: "v1.5.0"
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  # Prettier for any YAML, README
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.3.3" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v4.0.0-alpha.8"
  #   hooks:
  #     - id: prettier
  #       types_or: ["json", "yaml", "markdown", "html", "scss"]
  # General upkeep
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: no-commit-to-branch
        args: [--branch, main, --branch, release]
